### ISSUE TITLE
After running "gen", some committed files are modified

### ISSUE THREAD

**Issue by awrichar** [hyperledger-labs/zeto#52] opened 2024-09-03 18:43 UTC
From the [zkp/circuits](https://github.com/hyperledger-labs/zeto/tree/main/zkp/circuits) folder, if I run `npm run gen`, it modifies some of the committed files. Should these modified files be committed? Commit head is 8606ed9f030cd6132cf80b732f333b195f40d2d6.

This is the `git diff` after running the command:
```diff
diff --git a/solidity/contracts/lib/verifier_anon.sol b/solidity/contracts/lib/verifier_anon.sol
index 6ef9172..47dc246 100644
--- a/solidity/contracts/lib/verifier_anon.sol
+++ b/solidity/contracts/lib/verifier_anon.sol
@@ -68,7 +68,7 @@ contract Groth16Verifier_Anon {
     function verifyProof(uint[2] calldata _pA, uint[2][2] calldata _pB, uint[2] calldata _pC, uint[4] calldata _pubSignals) public view returns (bool) {
         assembly {
             function checkField(v) {
-                if iszero(lt(v, q)) {
+                if iszero(lt(v, r)) {
                     mstore(0, 0)
                     return(0, 0x20)
                 }
diff --git a/solidity/contracts/lib/verifier_anon_enc.sol b/solidity/contracts/lib/verifier_anon_enc.sol
index c402b26..8b01e78 100644
--- a/solidity/contracts/lib/verifier_anon_enc.sol
+++ b/solidity/contracts/lib/verifier_anon_enc.sol
@@ -77,7 +77,7 @@ contract Groth16Verifier_AnonEnc {
     function verifyProof(uint[2] calldata _pA, uint[2][2] calldata _pB, uint[2] calldata _pC, uint[7] calldata _pubSignals) public view returns (bool) {
         assembly {
             function checkField(v) {
-                if iszero(lt(v, q)) {
+                if iszero(lt(v, r)) {
                     mstore(0, 0)
                     return(0, 0x20)
                 }
diff --git a/solidity/contracts/lib/verifier_anon_enc_nullifier.sol b/solidity/contracts/lib/verifier_anon_enc_nullifier.sol
index 1a8a08d..eb236a3 100644
--- a/solidity/contracts/lib/verifier_anon_enc_nullifier.sol
+++ b/solidity/contracts/lib/verifier_anon_enc_nullifier.sol
@@ -86,7 +86,7 @@ contract Groth16Verifier_AnonEncNullifier {
     function verifyProof(uint[2] calldata _pA, uint[2][2] calldata _pB, uint[2] calldata _pC, uint[10] calldata _pubSignals) public view returns (bool) {
         assembly {
             function checkField(v) {
-                if iszero(lt(v, q)) {
+                if iszero(lt(v, r)) {
                     mstore(0, 0)
                     return(0, 0x20)
                 }
diff --git a/solidity/contracts/lib/verifier_anon_enc_nullifier_non_repudiation.sol b/solidity/contracts/lib/verifier_anon_enc_nullifier_non_repudiation.sol
index 37efa35..193c0bf 100644
--- a/solidity/contracts/lib/verifier_anon_enc_nullifier_non_repudiation.sol
+++ b/solidity/contracts/lib/verifier_anon_enc_nullifier_non_repudiation.sol
@@ -134,7 +134,7 @@ contract Groth16Verifier_AnonEncNullifierNonRepudiation {
     function verifyProof(uint[2] calldata _pA, uint[2][2] calldata _pB, uint[2] calldata _pC, uint[26] calldata _pubSignals) public view returns (bool) {
         assembly {
             function checkField(v) {
-                if iszero(lt(v, q)) {
+                if iszero(lt(v, r)) {
                     mstore(0, 0)
                     return(0, 0x20)
                 }
diff --git a/solidity/contracts/lib/verifier_anon_nullifier.sol b/solidity/contracts/lib/verifier_anon_nullifier.sol
index 710950c..0c99b01 100644
--- a/solidity/contracts/lib/verifier_anon_nullifier.sol
+++ b/solidity/contracts/lib/verifier_anon_nullifier.sol
@@ -77,7 +77,7 @@ contract Groth16Verifier_AnonNullifier {
     function verifyProof(uint[2] calldata _pA, uint[2][2] calldata _pB, uint[2] calldata _pC, uint[7] calldata _pubSignals) public view returns (bool) {
         assembly {
             function checkField(v) {
-                if iszero(lt(v, q)) {
+                if iszero(lt(v, r)) {
                     mstore(0, 0)
                     return(0, 0x20)
                 }
diff --git a/solidity/contracts/lib/verifier_anon_nullifier_kyc.sol b/solidity/contracts/lib/verifier_anon_nullifier_kyc.sol
index 23c24d9..980cbe2 100644
--- a/solidity/contracts/lib/verifier_anon_nullifier_kyc.sol
+++ b/solidity/contracts/lib/verifier_anon_nullifier_kyc.sol
@@ -80,7 +80,7 @@ contract Groth16Verifier_AnonNullifierKyc {
     function verifyProof(uint[2] calldata _pA, uint[2][2] calldata _pB, uint[2] calldata _pC, uint[8] calldata _pubSignals) public view returns (bool) {
         assembly {
             function checkField(v) {
-                if iszero(lt(v, q)) {
+                if iszero(lt(v, r)) {
                     mstore(0, 0)
                     return(0, 0x20)
                 }
diff --git a/solidity/contracts/lib/verifier_check_hashes_value.sol b/solidity/contracts/lib/verifier_check_hashes_value.sol
index f837377..825874c 100644
--- a/solidity/contracts/lib/verifier_check_hashes_value.sol
+++ b/solidity/contracts/lib/verifier_check_hashes_value.sol
@@ -62,7 +62,7 @@ contract Groth16Verifier_CheckHashesValue {
     function verifyProof(uint[2] calldata _pA, uint[2][2] calldata _pB, uint[2] calldata _pC, uint[2] calldata _pubSignals) public view returns (bool) {
         assembly {
             function checkField(v) {
-                if iszero(lt(v, q)) {
+                if iszero(lt(v, r)) {
                     mstore(0, 0)
                     return(0, 0x20)
                 }
diff --git a/solidity/contracts/lib/verifier_check_inputs_outputs_value.sol b/solidity/contracts/lib/verifier_check_inputs_outputs_value.sol
index 1b9945d..9c0da51 100644
--- a/solidity/contracts/lib/verifier_check_inputs_outputs_value.sol
+++ b/solidity/contracts/lib/verifier_check_inputs_outputs_value.sol
@@ -68,7 +68,7 @@ contract Groth16Verifier_CheckInputsOutputsValue {
     function verifyProof(uint[2] calldata _pA, uint[2][2] calldata _pB, uint[2] calldata _pC, uint[4] calldata _pubSignals) public view returns (bool) {
         assembly {
             function checkField(v) {
-                if iszero(lt(v, q)) {
+                if iszero(lt(v, r)) {
                     mstore(0, 0)
                     return(0, 0x20)
                 }
diff --git a/solidity/contracts/lib/verifier_nf_anon.sol b/solidity/contracts/lib/verifier_nf_anon.sol
index f2c2c3f..5b562d0 100644
--- a/solidity/contracts/lib/verifier_nf_anon.sol
+++ b/solidity/contracts/lib/verifier_nf_anon.sol
@@ -62,7 +62,7 @@ contract Groth16Verifier_NfAnon {
     function verifyProof(uint[2] calldata _pA, uint[2][2] calldata _pB, uint[2] calldata _pC, uint[2] calldata _pubSignals) public view returns (bool) {
         assembly {
             function checkField(v) {
-                if iszero(lt(v, q)) {
+                if iszero(lt(v, r)) {
                     mstore(0, 0)
                     return(0, 0x20)
                 }
diff --git a/solidity/contracts/lib/verifier_nf_anon_nullifier.sol b/solidity/contracts/lib/verifier_nf_anon_nullifier.sol
index 79cf3d8..ecb777e 100644
--- a/solidity/contracts/lib/verifier_nf_anon_nullifier.sol
+++ b/solidity/contracts/lib/verifier_nf_anon_nullifier.sol
@@ -65,7 +65,7 @@ contract Groth16Verifier_NfAnonNullifier {
     function verifyProof(uint[2] calldata _pA, uint[2][2] calldata _pB, uint[2] calldata _pC, uint[3] calldata _pubSignals) public view returns (bool) {
         assembly {
             function checkField(v) {
-                if iszero(lt(v, q)) {
+                if iszero(lt(v, r)) {
                     mstore(0, 0)
                     return(0, 0x20)
                 }
```

**Comment by Chengxuan** [comment] 2024-09-03 21:35
it's usually caused by version difference of snarkjs npm module (a dev dependency), did you run `npm i` before running `npm run gen` command follow [here](https://github.com/hyperledger-labs/zeto/tree/main/zkp/js#compile-the-circuits-and-generate-verification-keys-and-solidity-libraries), it should update the snarkjs to the latest version which will produce sol files committed in main branch.

**Closed** 2024-09-27 04:19 UTC
Labels: FAQ
